<a href="https://colab.research.google.com/github/pchroscicki/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Basic datatypes**

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)
type(x)

[1 3]


numpy.ndarray

-array attributes:

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.2, 1.4, 1.6])
x.dtype

dtype('float64')

2D Array

In [13]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

-attributes

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x.size

4

In [17]:
x.dtype

dtype('int64')

In [18]:
x = np.array([[1, 2, 3], [10, 9, 8]])
x.shape

(2, 3)

3D Array

In [19]:
x = np.array(
    [[[1, 2, 4],
    [1, 2, 6]],
     
    [[5, 6, 7],
     [8, 7, 6]],
    
    [[7, 8, 9],
     [7, 8, 7]]]
)
x

array([[[1, 2, 4],
        [1, 2, 6]],

       [[5, 6, 7],
        [8, 7, 6]],

       [[7, 8, 9],
        [7, 8, 7]]])

- attributes

In [20]:
x.ndim

3

In [21]:
x.shape

(3, 2, 3)

In [22]:
x.size

18

Typy danych

In [23]:
y = np.array([1, 2, 3])
y.dtype

dtype('int64')

In [24]:
y = np.array([1.1, 2.2, 3.3])
y.dtype

dtype('float64')

In [25]:
y = np.array([1, 2, 3], dtype=float)
print(y)
y.dtype

[1. 2. 3.]


dtype('float64')

In [26]:
y = np.array([1, 2, 3], dtype=complex)
print(y)
y.dtype

[1.+0.j 2.+0.j 3.+0.j]


dtype('complex128')

In [27]:
y = np.array([1.1, 2.2, 2.7, 3.3], dtype=int)
print(y)
y.dtype

[1 2 2 3]


dtype('int64')

In [28]:
y = np.array([True, False])
print(y)
y.dtype

[ True False]


dtype('bool')

In [29]:
y = np.array([1, 23, 104], dtype=np.int8)
y.dtype

dtype('int8')

In [30]:
y = np.array([1, 23, 104], dtype=np.uint8)
y.dtype

dtype('uint8')

# **Creation of arrays**

In [31]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [38]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [40]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [41]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [43]:
y = np.arange(15)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
y.reshape([3,5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
y.reshape([3, -1])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
y.reshape([-1, 3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# **Basic operations on arrays**

1D arrays

In [49]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [54]:
A + B

array([6, 0, 7, 4])

In [58]:
np.add( A , B)

array([6, 0, 7, 4])

In [51]:
A - B

array([0, 2, 1, 0])

In [59]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [52]:
A * B

array([ 9, -1, 12,  4])

In [60]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [53]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [61]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [55]:
A + 3

array([6, 4, 7, 5])

In [56]:
A * 2

array([6, 2, 8, 4])

In [57]:
A + 3 * B

array([12, -2, 13,  8])

2D arrays

In [67]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [68]:
X * Y

array([[6, 0],
       [2, 0]])

In [69]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [70]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [71]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# **Generating pseudo random numbers**

In [72]:
np.random.seed(0)

In [74]:
np.random.randn()

1.764052345967664

In [75]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [76]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [77]:
np.random.rand()

0.1965823616800535

In [78]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [79]:
np.random.rand(10, 4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [80]:
np.random.randint(10)

8

In [83]:
np.random.randint(low=10, high=101)

39

In [84]:
np.random.randint(low=10, high=101, size=10)

array([31, 35, 90, 70, 71, 93, 43, 42, 80, 95])

In [90]:
np.random.choice([4, 2, 1, 5, 7])

4

In [94]:
np.random.choice(['cat', 'dog', 'frog'])

'dog'

In [95]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.random.shuffle(data)
data

array([9, 2, 8, 7, 4, 5, 6, 1, 0, 3])

# **Basic functions in NumPy**

In [2]:
np.exp(1)

2.718281828459045

In [3]:
np.sqrt(9)

3.0

In [16]:
np.all([1, 4, 8, 9])

True

In [15]:
np.any([0, 0, 0, 1])

True

- to find min/max values:

In [8]:
A = np.random.rand(5)
A

array([0.15478154, 0.94943075, 0.16118486, 0.41386018, 0.21552954])

In [9]:
np.min(A)

0.154781539487032

In [10]:
np.max(A)

0.9494307466784287

In [15]:
np.argmin(A)

0

In [16]:
np.argmax(A)

1

In [17]:
np.argsort(A)

array([0, 2, 4, 3, 1])

- Simple statistics:

In [18]:
np.mean(A)

0.3789573737935005

In [19]:
np.median(A)

0.21552953948371512

In [20]:
np.std(A)

0.30034859909203393