<a href="https://colab.research.google.com/github/pchroscicki/data-science-bootcamp/blob/main/01_introduction/02_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

# **Norm and lenght of a vector**

In [3]:
# in 2D
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [4]:
np.linalg.norm(v1)

4.123105625617661

In [5]:
# in >2D
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

# **Distance between 2 datapoints**

In [6]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p -q)

5.0

In [7]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p -q)

5.0990195135927845

# **Multiplication of matrices**

In [9]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [10]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [11]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [13]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

# **Determinant of a matrix**

In [3]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

# **Matrix trace**

In [4]:
np.trace(A)

5

# **Identity matrix**

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# to change float data type to int
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# **Inverse matrix**

In [8]:
A

array([[ 2,  4],
       [-1,  3]])

In [10]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [11]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [13]:
# to reduce precision
np.set_printoptions(precision=4, suppress=True)

In [14]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

# **Transposed matrix**

In [4]:
A

array([[ 2,  4],
       [-1,  3]])

In [5]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [6]:
# the second option
A.T

array([[ 2, -1],
       [ 4,  3]])

# **Solving systems of equations**

Przykład:
2x + 4y = 10 ;
x - y = -1

In [7]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])

In [8]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])